# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'

prepare_react_native_project!

use_frameworks! :linkage => :dynamic

target 'united_cab_driver' do
  config = use_native_modules!

  pod 'GoogleUtilities'
  pod 'FirebaseCoreInternal'
  pod 'SDWebImage', '>= 5.18.0'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :new_arch_enabled => false, # IMPORTANT
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end
end