-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkANARTcSddDleuuB
b62C6A3SBG7hOLF3b+I+SERvntWgCgYIKoZIzj0DAQehRANCAARSj9giLMmCrXAn
zzoap5LtZlEaNPpGwgGMbNRTNNn+BAbNpAODOQT0xOci4pOau22ulAr+8+zFvJSz
6ItRKZVH
-----END PRIVATE KEY-----